apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-to-raw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest-to-raw
  template:
    metadata:
      labels:
        app: ingest-to-raw
    spec:
      containers:
      - name: ingest-to-raw
        image: quay.io/dparkes/ingest_to_raw:latest
        env:
        - name: SOURCE_ROLE_ARN
          value: "<your_source_role_arn>"
        - name: DESTINATION_ROLE_ARN
          value: "<your_destination_role_arn>"
        - name: OIDC_PROVIDER_URL
          value: "<your_OIDC_provider_URL>"
        - name: OIDC_CLIENT_SECRET
          value: "<your_OIDC_client_secret>"
        - name: OIDC_CLIENT_ID
          value: "<your_OIDC_client_ID>"
        - name: OIDC_USERNAME
          value: "<your_OIDC_username>"
        - name: OIDC_PASSWORD
          value: "<your_OIDC_password>"
        - name: S3_ENDPOINT_URL
          value: "<your_S3_endpoint_URL>"
        - name: STS_ENDPOINT_URL
          value: "<your_STS_endpoint_URL>"
